name: mxcube
channels:
  - tango-controls
  - conda-forge
  - anaconda
dependencies:
  - python=3.7
  - pip
  - pytest=6.2.1
  - gevent=1.3.7
  - greenlet=0.4.16
  - python-engineio=3.5.1
  - python-socketio=4.3.0
  - flask=1.1.2
  - flask-socketio=4.3.1
  - gevent-websocket=0.10.1
  - mock=4.0.3
  - jsonpickle=1.4.1
  - pillow=8.0.1
  - suds-jurko=0.6
  - python-ldap=3.3.1
  - lxml=4.6.2
  - ruamel.yaml=0.16.12
  - nodejs=10.13.0
  - scipy=1.5.3
  - opencv
  - requests
  - scandir
  - redis
  - redis-py
  - ffmpeg
  - pytango
  - werkzeug=1.0.1
  - bcrypt
  - flask-sqlalchemy
  - pytz
  - tzlocal

  - pip:
      - Flask-Session==0.3.2
      - git+https://github.com/marcus-oscarsson/python-v4l2.git
      - Louie-latest
      - spectree
      - git+https://github.com/mxcube/mxcubecore.git
      - flask-security-too