name: UI

on: [push, pull_request]

jobs:
  format:
    name: Format
    runs-on: ubuntu-latest

    # Skip `pull_request` runs on local PRs for which `push` runs are already triggered
    if: github.event_name == 'push' || github.event.pull_request.head.repo.full_name != github.repository

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install LDAP dependencies
        run: sudo apt-get -y install libsasl2-dev libldap2-dev libssl-dev

      - name: Set up Conda environment
        uses: mamba-org/setup-micromamba@v1
        with:
          micromamba-version: "latest"
          environment-file: conda-environment.yml
          cache-environment: true
          post-cleanup: "all"

      - name: Install MXCuBE
        run: pip install -e .

      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8.x

      - name: Cache UI dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/setup-pnpm/node_modules/.bin/store
            ~/.cache/Cypress
          key: cache-${{ runner.os }}-${{ hashFiles('pnpm-lock.yaml') }}
          restore-keys: ${{ runner.os }}-

      - name: Install UI dependencies
        run: pnpm --prefix ui install

      - name: Run Prettier
        run: pnpm --prefix ui prettier

  lint:
    name: Lint
    runs-on: ubuntu-latest

    # Skip `pull_request` runs on local PRs for which `push` runs are already triggered
    if: github.event_name == 'push' || github.event.pull_request.head.repo.full_name != github.repository

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install LDAP dependencies
        run: sudo apt-get -y install libsasl2-dev libldap2-dev libssl-dev

      - name: Set up Conda environment
        uses: mamba-org/setup-micromamba@v1
        with:
          micromamba-version: "latest"
          environment-file: conda-environment.yml
          cache-environment: true
          post-cleanup: "all"

      - name: Install MXCuBE
        run: pip install -e .

      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8.x

      - name: Cache UI dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/setup-pnpm/node_modules/.bin/store
            ~/.cache/Cypress
          key: cache-${{ runner.os }}-${{ hashFiles('pnpm-lock.yaml') }}
          restore-keys: ${{ runner.os }}-

      - name: Install UI dependencies
        run: pnpm --prefix ui install

      - name: Run ESLint
        run: pnpm --prefix ui eslint

  e2e:
    name: Test
    runs-on: ubuntu-latest

    # Skip `pull_request` runs on local PRs for which `push` runs are already triggered
    if: github.event_name == 'push' || github.event.pull_request.head.repo.full_name != github.repository

    # Service containers to run with `container-job`
    services:
      # Label used to access the service container
      redis:
        # Docker Hub image
        image: redis
        # Set health checks to wait until redis has started
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          # Maps port 6379 on service container to the host
          - 6379:6379

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install LDAP dependencies
        run: sudo apt-get -y install libsasl2-dev libldap2-dev libssl-dev

      - name: Set up Conda environment
        uses: mamba-org/setup-micromamba@v1
        with:
          micromamba-version: "latest"
          environment-file: conda-environment.yml
          cache-environment: true
          post-cleanup: "all"

      - name: Install MXCuBE
        run: pip install -e .

      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8.x

      - name: Cache UI dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/setup-pnpm/node_modules/.bin/store
            ~/.cache/Cypress
          key: cache-${{ runner.os }}-${{ hashFiles('pnpm-lock.yaml') }}
          restore-keys: ${{ runner.os }}-

      - name: Install UI dependencies
        run: pnpm --prefix ui install

      - name: Build UI
        run: pnpm --prefix ui build
        env:
          DISABLE_ESLINT_PLUGIN: true

      - name: Start MXCuBE-Web server
        run: |
          mxcubeweb-server -r ./test/HardwareObjectsMockup.xml/ --static-folder $(pwd)/ui/build/ -L debug &
          pnpm --prefix ui exec wait-on http://127.0.0.1:8081

      - name: Run Cypress
        run: pnpm --prefix ui e2e

      - uses: actions/upload-artifact@v3
        if: failure()
        with:
          name: debug
          retention-days: 3
          path: |
            ui/cypress/debug
            debug
